fix: path mismatch

diff --git a/.github/workflows/vite.yml b/.github/workflows/vite.yml
--- a/.github/workflows/vite.yml
+++ b/.github/workflows/vite.yml
@@ -49,7 +49,7 @@ jobs:
           npm_config_legacy_peer_deps: true
 
       - name: Build
-        run: pnpm run build
+        run: cd app/harmoneasy && pnpm run build
         timeout-minutes: 20
         env:
           NODE_ENV: production
@@ -57,16 +57,16 @@ jobs:
       - name: Check build output
         run: |
           echo "Build step completed"
-          ls -lah app/harmoneasy/dist-electron/ || echo "dist-electron folder not found"
+          ls -lah app/harmoneasy/dist/ || echo "dist folder not found"
 
       - name: List the build folder contents...
-        run: ls -lah app/harmoneasy/dist-electron/
+        run: ls -lah app/harmoneasy/dist/
 
       - name: Upload artifact
         id: deployment
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./app/harmoneasy/dist-electron
+          path: ./app/harmoneasy/dist
 
   deploy:
     # Add a dependency to the build job
